AllCops:
  NewCops: disable

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 1000
Metrics/MethodLength:
  Max: 50
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
