name: Specs

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Bundle Install
      run: |
        gem install bundler -v 2.2.3
        bundle install
    - name: RSpec
      run: |
        bundle exec rake spec
